### ISSUE TITLE
[Feature Request] Add a way to assign Fluid EMC

### ISSUE THREAD

**Issue by BraynStorm** [Rotatceps/EE3Helper#2]
The title says it all. Please :)

**Comment by Rotatceps** [comment]
Should be simple enough, I'll give it a shot.

**Comment by Rotatceps** [comment]
Added. 

Command is: ee3h add-fluid [fluid name] [emc value for 1000mB worth]

I'm going to make it so you can specify the amount of fluid (mB), but right now it assumes that you're setting the emc value for 1000mB worth.
